# docker compose --profile test build && docker compose --profile test up -d

services:
  bot:
    # production
    image: fizzbuzz:latest
    build: .
    env_file: .env
    restart: unless-stopped
    # depends_on: [db, redis]
    # keep logs modest so they don't fill disk
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    profiles:
      - prod
    volumes:
      - ./data:/app/data # so db data persists

  bot-test:
    image: fizzbuzz:latest
    build: .
    env_file: .env.test
    restart: no
    entrypoint: [ "/bin/sh", "-lc", "/app/fizzbuzz --token-override \"$$TESTING_TOKEN\" --debug" ]
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    profiles:
      - test
    volumes:
      - ./test_data:/app/data
