from io import BytesIO
from typing import Final

import discord

__author__: Final[str]
__license__: Final[str]

CSS_COLOR_NAME_TO_HEX: Final[dict[str, str]]

CSS_REDS: Final[dict[str, str]]
CSS_PINKS: Final[dict[str, str]]
CSS_ORANGES: Final[dict[str, str]]
CSS_YELLOWS: Final[dict[str, str]]
CSS_PURPLES: Final[dict[str, str]]
CSS_GREENS: Final[dict[str, str]]
CSS_BLUES: Final[dict[str, str]]
CSS_BROWNS: Final[dict[str, str]]
CSS_WHITES: Final[dict[str, str]]
CSS_GRAYS: Final[dict[str, str]]

HEX_TO_CSS_NAME: Final[dict[str, str]]

class ColorParseError(ValueError):
    def __init__(self, message: str | None = None) -> None: ...

class Color3:
    def __init__(self, r: int, g: int, b: int, /) -> None: ...
    def invert(self, /) -> Color3: ...
    def lerp(self, other: Color3, t: float, /) -> Color3: ...
    def relative_luminance(self) -> float: ...
    def lighten(self, percent: float, /) -> Color3: ...
    def darken(self, percent: float, /) -> Color3: ...
    @classmethod
    def random(cls, /) -> Color3: ...
    @classmethod
    def from_discord_color(cls, color: discord.Color, /) -> Color3: ...
    @classmethod
    def from_css_name(cls, name: str, /) -> Color3: ...
    @classmethod
    def from_hex6(cls, hex6: str, /) -> Color3: ...
    @classmethod
    def from_hsl(cls, h: float, s: float, l: float, /) -> Color3: ...
    @classmethod
    def from_int(cls, integer: int, /) -> Color3: ...
    def as_discord_color(self) -> discord.Color: ...
    def as_css_color(self) -> str | None: ...
    def as_rgb(self) -> tuple[int, int, int]: ...
    def as_hex6(self, *, hashtag: bool = False) -> str: ...
    def as_hsl(self) -> tuple[float, float, float]: ...
    def as_int(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

def validate_rgb(r: int, g: int, b: int, /) -> bool: ...
def validate_hex(hex6: str, /) -> bool: ...
def generate_color_image(
    color: Color3, /, *, size: tuple[int, int] = (100, 100)
) -> BytesIO: ...
