# pylint: disable=all

from io import BytesIO
from typing import Final

import discord

__author__: Final[str]
__license__: Final[str]

RGB_MAX: Final[int]

REDS: Final[dict[str, str]]
PINKS: Final[dict[str, str]]
ORANGES: Final[dict[str, str]]
YELLOWS: Final[dict[str, str]]
PURPLES: Final[dict[str, str]]
GREENS: Final[dict[str, str]]
BLUES: Final[dict[str, str]]
BROWNS: Final[dict[str, str]]
WHITES: Final[dict[str, str]]
GRAYS: Final[dict[str, str]]
COLORS: Final[dict[str, str]]

def get_color_key(hex6: str, /) -> str | None: ...
def hex_is_valid(hex6: str, /) -> bool: ...
def rgb_component_is_valid(value: int, /) -> bool: ...
def hex2rgb(hex6: str, /) -> tuple[int, int, int]: ...
def rgb2hex(r: int, g: int, b: int, /) -> str: ...
def random_hex() -> str: ...
def random_rgb() -> tuple[int, int, int]: ...
def invert_rgb(r: int, g: int, b: int, /) -> tuple[int, int, int]: ...
def invert_hex(hex6: str, /) -> str: ...
def create_color_role_name(member: discord.Member, /) -> str: ...
def generate_color_image(hex6: str) -> BytesIO: ...
